services:
  r2:
    container_name: r2
    restart: always
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio:/data:Z
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    command: server --console-address ":9001" /data
    network_mode: host
    healthcheck:
      test: curl --fail http://localhost:9000/minio/health/live || exit 1
      interval: 5s
      timeout: 30s
      retries: 5
      start_period: 10s
  create-buckets:
    image: minio/mc
    depends_on:
      r2:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add minio http://localhost:9000 admin password;
      /usr/bin/mc mb minio/cyoa-assets;
      /usr/bin/mc mb minio/cyoa-stories;
      /usr/bin/mc anonymous set public minio/cyoa-assets;
      exit 0;
      "
    network_mode: host