version: '3.5'
services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:Z
      - ./ssl/domain.crt:/root/ssl/domain.crt:Z
      - ./ssl/domain.key:/root/ssl/domain.key:Z
    network_mode: host

  r2:
    container_name: r2
    restart: always
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio:/data:Z
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    command: server --console-address ":9001" /data
    networks:
      - cyoa
  create-buckets:
    image: minio/mc
    depends_on:
      - r2
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add minio http://r2:9000 admin password;
      /usr/bin/mc mb minio/cyoa-assets;
      /usr/bin/mc mb minio/cyoa-stories;
      /usr/bin/mc policy set public minio/cyoa-assets;
      exit 0;
      "

networks:
    cyoa:
        name: cyoa
