# deploy workflow
name: "master"

on:
  push:
    branches:
      - master
jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout"
      uses: actions/checkout@v4
    - uses: actions/setup-node@v3
      with:
        node-version: 18.18.2
    - name: "Build backend"
      run: |
        cd ./server
        npm i
        npm run build:prod
    - name: "Deploy"
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: 22
        strip_components: 1
        rm: true
        source: "server/dist,server/package.json,server/package-lock.json,server/db,server/tsconfig.json"
        target: ${{ secrets.WORK_DIR }}
    - uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: 22
        script: |
          cd ${{ secrets.WORK_DIR }}
          npm i --omit=dev
          npm run db:migrate
          cd ..
          pm2 startOrReload ecosystem.config.cjs --update-env
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout"
      uses: actions/checkout@v4
    - uses: actions/setup-node@v3
      with:
        node-version: 18.18.2
    - name: "Build"
      run: |
        cd ./client
        npm i
        ENV=PRODUCTION npm run build
    - name: Publish to Cloudflare Pages
      uses: cloudflare/pages-action@v1
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        projectName: cyoa
        directory: client/build
        branch: main